Vagrant.configure("2") do |config|
  # Define the first VM
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.hostname = "master"
    ubuntu1.vm.network "private_network", ip: "192.168.33.10"
  end

  # Define the second VM
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/focal64"
    ubuntu2.vm.hostname = "slave"
    ubuntu2.vm.network "private_network", ip: "192.168.33.11"
  end
end
